[package]
name = "ruby-appimage-wrapper"
version = "0.1.0"
authors = ["Andrey Vasilyev <andrey.vasilyev@fruct.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.15.0"
exitcode = "1.1.2"