version: '3.7'

services:
  registry:
    image: registry:2.7.1
    ports:
      - mode: host
        target: 5000
        published: 5000
    volumes:
      - /srv/repository/docker-registry/registry:/var/lib/registry
      - /srv/repository/docker-registry/auth:/auth
      - /etc/ssl/:/cert
    restart: always
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: MariaDB CI Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/docker-registry.htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /cert/certs/mariadb.net.origin.crt
      REGISTRY_HTTP_TLS_KEY: /cert/private/mariadb.net.origin.key
      REGISTRY_HTTP_SECRET: $SECRET
